# Netlify CMS Configuration File

# The backend option specifies how to access the content for your site
backend:
  name: git-gateway
  branch: main # The branch to update (optional; defaults to master)

# Uncomment below to enable drafts https://www.netlifycms.org/docs/add-to-your-site/#editorial-workflow
# publish_mode: editorial_workflow

# Uncomment below to enable a link to your published site in the header bar of Netlify CMS
# site_url: https://eleventy-netlify-boilerplate.netlify.app/

media_folder: "static/img" # Media files will be stored in the repo under images/uploads

collections:
  # Our blog posts
  - name: "posts" # Used in routes, e.g., /admin/collections/blog
    label: "Post" # Used in the UI
    folder: "posts/" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Alt Description (kort beskrivelse af billedet for synshæmmet)", name: "alt", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Order (mindst kommer først)", name: "order", widget: "string" }

  # Our pages e.g. About
  - name: "contact"
    label: "Contact"
    files:
      - name: "contact"
        label: "Contact"
        file: "pages/contact.md"
        fields:
          - { label: "Contact", name: "contact", widget: "string" }


  - name: "cv"
    label: "Cv"
    files:
      - name: "cv"
        label: "CV"
        file: "pages/cv.md"
        fields:
          - { label: "Cv tekst", name: "body", widget: "markdown" }
